### ISSUE TITLE
Changing the licence and removing the AUTHORS file is not ok.

### ISSUE THREAD

**Issue by batiste** [ArabellaTech/django-basic-cms#12]
Guys you are in violation of the licence here.

"Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer."

You need to put back the original licence with my name as well as the AUTHORS file with all the contributors.

I would really liked a real fork instead of a silent clone of the repository without any history.

edit: change the phrasing to not be so incendiary.

**Comment by patrys** [comment]
@remik, @jacoor, I am disappoint.

**Comment by jpic** [comment]
Not cool.

**Comment by davide-ceretti** [comment]
:-1:

**Comment by tomchristie** [comment]
Folks could you just leave off for a moment before all jumping on the bandwagon?
Mellow out & give the maintainers a chance to address the copyright line on the license.

**Comment by batiste** [comment]
@tomchristie sure, I am all for letting the peoples at Arabella Tech the time to react on this. I am curious to hear what they have to say.

**Comment by remik** [comment]
Sorry, I don't remember why we did this way. Probably something broken during global rename. 
I will be happy to fix it but I need some sleep now (just back home after 10h flight)

**Comment by batiste** [comment]
@remik thanks for your explanation. No problem take the time you need. Sorry I was a bit rude on this matter. Cheers.
Batiste

**Comment by remik** [comment]
Sorry for breaking it. Fixed. Thanks for checking.
